# Generated by Django 2.1.5 on 2019-01-16 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=5)),
                ('serialNuber', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N/A', 'nAn')], max_length=1)),
                ('birthday_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastVisit_date', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_A', models.PositiveIntegerField()),
                ('index_B', models.PositiveIntegerField()),
                ('index_C', models.PositiveIntegerField()),
                ('avg_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TherapyDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transmission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
                ('statistics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Statistics')),
            ],
        ),
    ]
