# Generated by Django 2.1.5 on 2019-01-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190116_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
    ]
