# Generated by Django 2.1.5 on 2019-01-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190116_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('contacts', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organisation'),
        ),
    ]
