# Generated by Django 2.1.5 on 2019-01-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190117_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Latitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Longitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Date')),
                ('latitude', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Latitude')),
                ('longitude', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Longitude')),
            ],
        ),
    ]
