# Generated by Django 2.1.5 on 2019-01-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_date_latitude_longitude_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Date', unique=False),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='latitude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Latitude', unique=False),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='longitude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Longitude', unique=False),
        ),
    ]
