# Generated by Django 2.1.5 on 2019-01-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190121_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='latitude',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='longitude',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='temperature',
            name='importedFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ImportedFile'),
        ),
    ]
