# Generated by Django 2.1.5 on 2019-01-21 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190121_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='longitude',
            name='bulk_ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=320),
            preserve_default=False,
        ),
    ]
