# Generated by Django 2.1.5 on 2019-01-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_longitude_bulk_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ImportedFile'),
        ),
    ]
